### ISSUE TITLE
Question about VR/NON-VR

### ISSUE THREAD

**Issue by kodxana** [brandonmousseau/vhvr-mod#1]
Can VR players and non VR players play on that same dedicated server. And if yes how non VR players will see VR players animations?

**Comment by brandonmousseau** [comment]
I actually haven't played any multiplayer myself, but some users have reported it works - I will need to test it. I'm not aware of anything in my mod that would interfere with multiplayer stuff though.

**Comment by brandonmousseau** [comment]
By all reported accounts, this should work fine - please open new issues if you have any problems doing this.
