### ISSUE TITLE
Allow HUD scaling

### ISSUE THREAD

**Issue by walz-jls** [brandonmousseau/vhvr-mod#121]
Hi,
I'm playing on a wide-fov headset (pimax 8k X) and the HUD (mini map, and inventory when opened) gets pushed to the left and right sides, so you have to roll your eyes to the maximum to be able to read and use it.
And option to scale it down or recenter it would greatly increase the comfort of use.

**Comment by brandonmousseau** [comment]
What is the game's resolution set too? Try setting it to 1080p and restarting the game, as this will change the UI scale. Not sure what it will look like in the pimax tho. It's unlikely we'll spend too much time working on a feature like this as we are working on completely modifying the UI so it is custom for VR.

**Comment by walz-jls** [comment]
1080p did help a bit by making the "squares" bigger thus taking a bit more place towards the middle.
The extremes are still far out in the corner though.
Still, it's a QOL thing and I completely understand that you're not gonna work on that if you're changing it anyway.
Thanks for the awesome work !
