### ISSUE TITLE
Head movement causes too much translation of player position 

### ISSUE THREAD

**Issue by loganlemmon** [brandonmousseau/vhvr-mod#122]
Build: #0.7.0
Devices: Valve Index
Environment: Windows

Repro Steps:
1. Launch VHVR
2. Load into world
3. Pan the head left, right, up, down
4. Observe player position translating too quickly in world space
5. Experience motion sickness 😆 

Notes: The world seems to move _more_ than it should compared to moving my head in other games or in real life. When looking straight down the effect is much more noticeable.

**Comment by brandonmousseau** [comment]
this should be fixed in newest versions
