### ISSUE TITLE
Mouse is still captured by the game even when unfocused

### ISSUE THREAD

**Issue by matejdro** [brandonmousseau/vhvr-mod#137]
Not sure if this is the Mod's fault or Valheim's fault, but it seems like Mouse is still captured by the game even when unfocused.

Using your desktop through the Steam's desktop feature or through the Desktop+ is very glitchy (sometimes it will work, sometimes you have to perform extra alt tab maneuvers to get mouse cursor to unstick, sometimes mouse cursor will just jump around to the center on every click).

**Comment by brandonmousseau** [comment]
Yea its only supposed to lock when it has focus, but I think this is a bug in unity that prevents it from working correctly. This was really just a hold-over from when the game was mouse & keyboard only. You can change an option in the config file ```UnlockDesktopCursor ``` to true to prevent this from happening at all. A future update will make this true by default.

**Comment by matejdro** [comment]
Thanks, it helped.
