### ISSUE TITLE
View direction is incorrect after Patch 0.204.4

### ISSUE THREAD

**Issue by 0beron** [brandonmousseau/vhvr-mod#141]
Valheim updated to new unity version today, and the headset view direction is almost upside down, affecting the menu background and in game, but not the gui overlay.

Feels like the roll axis is rotating twice as fast - if I invert the head set then the sky is still down. It's the correct way up when the headset is rolled to 90 degrees.

**Comment by brandonmousseau** [comment]
a4415848cd24cc5ad70858bfa7a183b8e5789f19
