### ISSUE TITLE
HUD Patch 3 - Map on boat

### ISSUE THREAD

**Issue by kalleknall** [brandonmousseau/vhvr-mod#150]
Hi, is there any setting to hold the map in front of me if i sail a boat ? 

The map will stay at its position. on land not a big problem, but on sea a bad idea ;-)

**Comment by brandonmousseau** [comment]
yea, that's something we plan to do actually (we talked about it a bunch in the discord :) )

**Comment by kalleknall** [comment]
Great :-)

THX for your work !
