### ISSUE TITLE
Can't sleep

### ISSUE THREAD

**Issue by Sajeg** [brandonmousseau/vhvr-mod#200]
I can't sleep when I am clicking on a bed.  I just get teleported on the bed, but I don't sleep. 
Or am I just stupid?

**Comment by fieryWaters** [comment]
I haven't had any trouble sleeping, but the Quest controller mappings are odd

**Comment by brandonmousseau** [comment]
Hey, sorry, we can't reproduce this. If you have any other mods installed or anything, those might cause some conflicts. Otherwise we'll need more information on exactly how to reproduce the bug.
