### ISSUE TITLE
No uninstallation instructions? 

### ISSUE THREAD

**Issue by fieryWaters** [brandonmousseau/vhvr-mod#204]
I know I can uninstall Valheim, delete the leftover files, and redownload, but it would be helpful to have official instructions.

**Comment by brandonmousseau** [comment]
If you want to uninstall the mod, you can simply remove the plugin DLL from the BepInEx folder - there shouldn't be any consequence to having the other files loose in the directory. If you want to really uninstall, basically any files that are in the zip file would need to be deleted from your game directories (the mod doesn't replace any existing game files). 

You can also temporarily disable the mod through the "ModEnabled" option in the config file.
