### ISSUE TITLE
Certain UI elements can't be "clicked" in VR.

### ISSUE THREAD

**Issue by fozzibab** [brandonmousseau/vhvr-mod#343]
Certain elements of the UI aren't responding when being clicked on in VR using the Index controllers, but other UI elements behave normally. This basically makes it impossible to play, as the "start" button on the world selection screen can't be clicked. It changes color as if it's being clicked on, but nothing happens. Browsing for servers seems to work (although no servers show up in the list), and it's possible to create a new world and enter a name and seed, but nothing happens when interacting with the start button. 

Additionally While it's possible create a new character or select an existing one, modifying the "hair" and "beard" options isn't possible, although renaming the character, changing the gender, and accepting the character work just fine. 

The game is frontmost active, and I can't figure out what is going on with it. Any help would be appreciated!

Uploaded my LogOutput for the fun of it.
[valheim_LogOutput.log](https://github.com/brandonmousseau/vhvr-mod/files/11059360/valheim_LogOutput.log)

**Comment by brandonmousseau** [comment]
I mentioned on nexus the mod is broken after the last game update. Wip to fix all issues. You can join the discord if you'd like an early build.

**Comment by fozzibab** [comment]
Got it, apologies for that, I missed that on the nexus page 👍 I'll join the discord and grab an early build.
