### ISSUE TITLE
Vr wont start Quest 3

### ISSUE THREAD

**Issue by Pijuten** [brandonmousseau/vhvr-mod#373]
Log

[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (12/15/2023 4:26:49 PM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity v2022.3.12.5236448
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [ValheimVR Mod 0.9.12]
[Info   : Unity Log] [ValheimVRMod] Perform pre-initialization...
[Info   : Unity Log] [ValheimVRMod] ValheimVR Mod Awakens!
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] 12/15/2023 16:33:47: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] 12/15/2023 16:33:47: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] Privilege Multiplayer is not known on this platform. Privilege therefore is granted without check...
[Warning: Unity Log] Privilege UserGeneratedContent is not known on this platform. Privilege therefore is granted without check...
[Warning: Unity Log] Privilege CrossPlay is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] [ValheimVRMod]  [DEBUG] Skipping KBandMouse_FindHoverObjectPatch patch.
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA SetProjectionMatrix
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA Render
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA GetJitterVector
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA reference
[Info   : Unity Log] Patched TAA ResetHistory
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Settings and name UpdateBindings and parameters 
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void ValheimVRMod.Patches.PatchEndBindKey::Postfix()
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
ValheimVRMod.Patches.HarmonyPatcher.DoPatching () (at <1cc36db240a341c3998f2e9eb69297ac>:0)
ValheimVRMod.ValheimVRMod.StartValheimVR () (at <1cc36db240a341c3998f2e9eb69297ac>:0)
ValheimVRMod.ValheimVRMod.Start () (at <1cc36db240a341c3998f2e9eb69297ac>:0)

[Info   : Unity Log] 12/15/2023 16:33:48: Starting to load scene:start

[Info   : Unity Log] [ValheimVRMod]  [DEBUG] SoftwareCursor: OnEnable()
[Info   : Unity Log] [ValheimVRMod]  [DEBUG] Found Cursor texture
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 12/15/2023 16:33:54: Using environment steamid 892970

[Info   : Unity Log] 12/15/2023 16:33:54: Using steam APPID:892970

[Info   : Unity Log] 12/15/2023 16:33:54: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 12/15/2023 16:33:54: Steam initialized, persona:Cheesus Reincarnated

[Info   : Unity Log] 12/15/2023 16:33:54: PlayFab custom ID set to "Steam_76561198289386188"

[Info   : Unity Log] 12/15/2023 16:33:54: Using default prefs

[Info   : Unity Log] 12/15/2023 16:33:54: Valheim version: 0.217.38 (network version 20)

[Info   : Unity Log] Trying to set graphic mode to 'Custom'
[Info   : Unity Log] Graphic mode 'Custom' is not or no longer supported. Fallback to default mode for platform...
[Info   : Unity Log] Graphic mode 'Custom' applied!
[Info   : Unity Log] 12/15/2023 16:33:54: Worldgenerator version setup:2

[Info   : Unity Log] 12/15/2023 16:33:54: Render threading mode:MultiThreaded

[Warning: Unity Log] 12/15/2023 16:33:54: Set button "CamZoomIn" to None!

[Warning: Unity Log] 12/15/2023 16:33:54: Set button "CamZoomOut" to None!

[Warning: Unity Log] 12/15/2023 16:33:54: Set button "CamZoomIn" to None!

[Warning: Unity Log] 12/15/2023 16:33:54: Set button "CamZoomOut" to None!

[Info   : Unity Log] 12/15/2023 16:33:54: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 12/15/2023 16:33:54: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 12/15/2023 16:33:54: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 12/15/2023 16:33:54: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 12/15/2023 16:33:54: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Warning: Unity Log] 12/15/2023 16:33:54: Missing audio clip in music respawn

[Info   : Unity Log] 12/15/2023 16:33:54: Checking for installed DLCs

[Info   : Unity Log] 12/15/2023 16:33:54: DLC:beta installed:False

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimVRMod.VRCore.UI.ConfigSettings.generatePrefabs () (at <1cc36db240a341c3998f2e9eb69297ac>:0)
ValheimVRMod.VRCore.UI.ConfigSettings.instantiate (UnityEngine.Transform mList, UnityEngine.Transform mParent, UnityEngine.GameObject sPrefab) (at <1cc36db240a341c3998f2e9eb69297ac>:0)
ValheimVRMod.Patches.PatchFejd.Postfix (FejdStartup __instance) (at <1cc36db240a341c3998f2e9eb69297ac>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::SetupGui>(FejdStartup)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

[Info   : Unity Log] 12/15/2023 16:33:54: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 12/15/2023 16:33:55: PlayFab logged in as "Steam_76561198289386188"

[Info   : Unity Log] 12/15/2023 16:33:55: PlayFab local entity ID is DC4F3E6A82D2D4BA

**Comment by brandonmousseau** [comment]
mod currently needs a patch to work with latest valheim version that released a few days ago

**Comment by Pijuten** [comment]
Thanks for the info and thanks for your work :))
