### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by mbgroot** [brandonmousseau/vhvr-mod#40]
Good afternoon. Is there a brief assembly instruction? this branch - https://github.com/brandonmousseau/vhvr-mod/tree/vr_body_prototype

**Comment by brandonmousseau** [comment]
you will need Unity editor 2019.42f1 and getdependencies (game dlls + [BepInEx](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) and preferrably visual studio 2019 to edit the CS project
Steps to build:
1. Update the "CommonDir" directory in the cs proj file to the path where your game is installed
2. First build the Unity project
2. Build the visual studio project

Mod contents will automatically be copied to your game's directory post build and will also be in copied locally to the project folder ValheimVRMod/release

If you would like to contribute or have questions, best to join the discord and we can help interactively: https://discord.gg/ZFSCSDe

**Comment by brandonmousseau** [comment]
feel free to re-open if you have additional questions
