### ISSUE TITLE
sign editing

### ISSUE THREAD

**Issue by Andi1986** [brandonmousseau/vhvr-mod#49]
"When I edit a sign, I can't seem to find an input to close the sign-editing window."

**Comment by brandonmousseau** [comment]
regarding sign editing - would be pretty sweet if we could have some virtual keyboard to input text - I wonder if there is something built into steamvr that we could use (or if we could just build some custom keyboard UI)  - not super important but would be nice to have

**Comment by brandonmousseau** [comment]
18520d6d003fbdb993724e5c33b0b179e76f0301

**Comment by brandonmousseau** [comment]
I tested this out on index - worked great for me. Think we can close now?

**Comment by Andi1986** [comment]
will be fixed in next release
