### ISSUE TITLE
QuickMenu UI parented to horizontal head movement rather than controller position.

### ISSUE THREAD

**Issue by CedricKnapp** [brandonmousseau/vhvr-mod#80]
The Quickmenu is a great idea, but this current bug makes using it very difficult. Once I open it, the position of the UI is parented to the headset "Yaw" rotation. Movement of the motion controller allows selection of quickmenu items to occur, but to be able to use it effectively, head movement needs to stop for the duration of using the quick menu.

Please see attached Video of bug issue: https://imgur.com/a/KwqDSnh

Using an Oculus Quest 2 with Virtual Desktop.

**Comment by brandonmousseau** [comment]
This is already fixed in 5dd5525b3b6629cdb121ea28b7246afd217e029c and will be in the next release

**Comment by CedricKnapp** [comment]
Sorry I didn't see the pr with the fix before I created the issue. Happy to see a fix is has been created to address it, thanks!
