### ISSUE TITLE
separate holsters for left/right

### ISSUE THREAD

**Issue by brandonmousseau** [brandonmousseau/vhvr-mod#91]
Report:
```
Hi,
I've noted, if you have equipped with a shield plus an item/weapon and you tried to holster both items (grab over shoulders for
both items with each controllers), only the last one is memorized.

Thanks.
```

Would be nice feature if we had separate holsters for left and right hands that remembered whatever weapon equipped there.

Maybe long term we might even have some custom holster solution like VRIK for SkyrimVR.

**Comment by Andi1986** [comment]
fixed in https://github.com/brandonmousseau/vhvr-mod/commit/72a264fbda2631b7b013cdb1d6f0949684d44467
